/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.welflex.examples.inventory;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class LocationSku extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1106916606345925747L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LocationSku\",\"namespace\":\"io.welflex.examples.inventory\",\"fields\":[{\"name\":\"location\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"sku\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LocationSku> ENCODER =
      new BinaryMessageEncoder<LocationSku>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LocationSku> DECODER =
      new BinaryMessageDecoder<LocationSku>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<LocationSku> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<LocationSku> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<LocationSku>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this LocationSku to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a LocationSku from a ByteBuffer. */
  public static LocationSku fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String location;
  @Deprecated public java.lang.String sku;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LocationSku() {}

  /**
   * All-args constructor.
   * @param location The new value for location
   * @param sku The new value for sku
   */
  public LocationSku(java.lang.String location, java.lang.String sku) {
    this.location = location;
    this.sku = sku;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return location;
    case 1: return sku;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: location = (java.lang.String)value$; break;
    case 1: sku = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'location' field.
   * @return The value of the 'location' field.
   */
  public java.lang.String getLocation() {
    return location;
  }

  /**
   * Sets the value of the 'location' field.
   * @param value the value to set.
   */
  public void setLocation(java.lang.String value) {
    this.location = value;
  }

  /**
   * Gets the value of the 'sku' field.
   * @return The value of the 'sku' field.
   */
  public java.lang.String getSku() {
    return sku;
  }

  /**
   * Sets the value of the 'sku' field.
   * @param value the value to set.
   */
  public void setSku(java.lang.String value) {
    this.sku = value;
  }

  /**
   * Creates a new LocationSku RecordBuilder.
   * @return A new LocationSku RecordBuilder
   */
  public static io.welflex.examples.inventory.LocationSku.Builder newBuilder() {
    return new io.welflex.examples.inventory.LocationSku.Builder();
  }

  /**
   * Creates a new LocationSku RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LocationSku RecordBuilder
   */
  public static io.welflex.examples.inventory.LocationSku.Builder newBuilder(io.welflex.examples.inventory.LocationSku.Builder other) {
    return new io.welflex.examples.inventory.LocationSku.Builder(other);
  }

  /**
   * Creates a new LocationSku RecordBuilder by copying an existing LocationSku instance.
   * @param other The existing instance to copy.
   * @return A new LocationSku RecordBuilder
   */
  public static io.welflex.examples.inventory.LocationSku.Builder newBuilder(io.welflex.examples.inventory.LocationSku other) {
    return new io.welflex.examples.inventory.LocationSku.Builder(other);
  }

  /**
   * RecordBuilder for LocationSku instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LocationSku>
    implements org.apache.avro.data.RecordBuilder<LocationSku> {

    private java.lang.String location;
    private java.lang.String sku;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.welflex.examples.inventory.LocationSku.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.location)) {
        this.location = data().deepCopy(fields()[0].schema(), other.location);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sku)) {
        this.sku = data().deepCopy(fields()[1].schema(), other.sku);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing LocationSku instance
     * @param other The existing instance to copy.
     */
    private Builder(io.welflex.examples.inventory.LocationSku other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.location)) {
        this.location = data().deepCopy(fields()[0].schema(), other.location);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sku)) {
        this.sku = data().deepCopy(fields()[1].schema(), other.sku);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'location' field.
      * @return The value.
      */
    public java.lang.String getLocation() {
      return location;
    }

    /**
      * Sets the value of the 'location' field.
      * @param value The value of 'location'.
      * @return This builder.
      */
    public io.welflex.examples.inventory.LocationSku.Builder setLocation(java.lang.String value) {
      validate(fields()[0], value);
      this.location = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'location' field has been set.
      * @return True if the 'location' field has been set, false otherwise.
      */
    public boolean hasLocation() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'location' field.
      * @return This builder.
      */
    public io.welflex.examples.inventory.LocationSku.Builder clearLocation() {
      location = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sku' field.
      * @return The value.
      */
    public java.lang.String getSku() {
      return sku;
    }

    /**
      * Sets the value of the 'sku' field.
      * @param value The value of 'sku'.
      * @return This builder.
      */
    public io.welflex.examples.inventory.LocationSku.Builder setSku(java.lang.String value) {
      validate(fields()[1], value);
      this.sku = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sku' field has been set.
      * @return True if the 'sku' field has been set, false otherwise.
      */
    public boolean hasSku() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sku' field.
      * @return This builder.
      */
    public io.welflex.examples.inventory.LocationSku.Builder clearSku() {
      sku = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LocationSku build() {
      try {
        LocationSku record = new LocationSku();
        record.location = fieldSetFlags()[0] ? this.location : (java.lang.String) defaultValue(fields()[0]);
        record.sku = fieldSetFlags()[1] ? this.sku : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LocationSku>
    WRITER$ = (org.apache.avro.io.DatumWriter<LocationSku>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LocationSku>
    READER$ = (org.apache.avro.io.DatumReader<LocationSku>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
